//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.SygnalizacjaIII {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLCEmulator.SygnalizacjaIII.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaria.
        /// </summary>
        internal static string msgAwaria {
            get {
                return ResourceManager.GetString("msgAwaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak &quot;Zielonej Fali&quot;.
        /// </summary>
        internal static string msgFala {
            get {
                return ResourceManager.GetString("msgFala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z urządzeniem.
        /// </summary>
        internal static string msgNoConnection {
            get {
                return ResourceManager.GetString("msgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj symulację.
        /// </summary>
        internal static string msgPauseSimulation {
            get {
                return ResourceManager.GetString("msgPauseSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % pojazdów opuściło skrzyżowanie bezkolizyjnie..
        /// </summary>
        internal static string msgPodsumowanie {
            get {
                return ResourceManager.GetString("msgPodsumowanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 1.
        /// </summary>
        internal static string msgPojazd1 {
            get {
                return ResourceManager.GetString("msgPojazd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 10.
        /// </summary>
        internal static string msgPojazd10 {
            get {
                return ResourceManager.GetString("msgPojazd10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 2.
        /// </summary>
        internal static string msgPojazd2 {
            get {
                return ResourceManager.GetString("msgPojazd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 3.
        /// </summary>
        internal static string msgPojazd3 {
            get {
                return ResourceManager.GetString("msgPojazd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 4.
        /// </summary>
        internal static string msgPojazd4 {
            get {
                return ResourceManager.GetString("msgPojazd4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 5.
        /// </summary>
        internal static string msgPojazd5 {
            get {
                return ResourceManager.GetString("msgPojazd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 6.
        /// </summary>
        internal static string msgPojazd6 {
            get {
                return ResourceManager.GetString("msgPojazd6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 7.
        /// </summary>
        internal static string msgPojazd7 {
            get {
                return ResourceManager.GetString("msgPojazd7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 8.
        /// </summary>
        internal static string msgPojazd8 {
            get {
                return ResourceManager.GetString("msgPojazd8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojazd 9.
        /// </summary>
        internal static string msgPojazd9 {
            get {
                return ResourceManager.GetString("msgPojazd9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość symulacji.
        /// </summary>
        internal static string msgSimulationSpeed {
            get {
                return ResourceManager.GetString("msgSimulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom symulację.
        /// </summary>
        internal static string msgStartSimulation {
            get {
                return ResourceManager.GetString("msgStartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij test.
        /// </summary>
        internal static string msgStartTest {
            get {
                return ResourceManager.GetString("msgStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj test.
        /// </summary>
        internal static string msgStopTest {
            get {
                return ResourceManager.GetString("msgStopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 1.
        /// </summary>
        internal static string msgTest_opuszczenie1 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 10.
        /// </summary>
        internal static string msgTest_opuszczenie10 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 2.
        /// </summary>
        internal static string msgTest_opuszczenie2 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 3.
        /// </summary>
        internal static string msgTest_opuszczenie3 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 4.
        /// </summary>
        internal static string msgTest_opuszczenie4 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 5.
        /// </summary>
        internal static string msgTest_opuszczenie5 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 6.
        /// </summary>
        internal static string msgTest_opuszczenie6 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 7.
        /// </summary>
        internal static string msgTest_opuszczenie7 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 8.
        /// </summary>
        internal static string msgTest_opuszczenie8 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzyżowanie opuszcza pojazd 9.
        /// </summary>
        internal static string msgTest_opuszczenie9 {
            get {
                return ResourceManager.GetString("msgTest_opuszczenie9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 1.
        /// </summary>
        internal static string msgTest1 {
            get {
                return ResourceManager.GetString("msgTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 10.
        /// </summary>
        internal static string msgTest10 {
            get {
                return ResourceManager.GetString("msgTest10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 2.
        /// </summary>
        internal static string msgTest2 {
            get {
                return ResourceManager.GetString("msgTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 3.
        /// </summary>
        internal static string msgTest3 {
            get {
                return ResourceManager.GetString("msgTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 4.
        /// </summary>
        internal static string msgTest4 {
            get {
                return ResourceManager.GetString("msgTest4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 5.
        /// </summary>
        internal static string msgTest5 {
            get {
                return ResourceManager.GetString("msgTest5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 6.
        /// </summary>
        internal static string msgTest6 {
            get {
                return ResourceManager.GetString("msgTest6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 7.
        /// </summary>
        internal static string msgTest7 {
            get {
                return ResourceManager.GetString("msgTest7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 8.
        /// </summary>
        internal static string msgTest8 {
            get {
                return ResourceManager.GetString("msgTest8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na skrzyżowaniu pojawił się pojazd 9.
        /// </summary>
        internal static string msgTest9 {
            get {
                return ResourceManager.GetString("msgTest9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLIZJA ŚWIATEŁ.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLIZJA POJAZDÓW.
        /// </summary>
        internal static string msgWarning_car {
            get {
                return ResourceManager.GetString("msgWarning_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec testu.
        /// </summary>
        internal static string testEnd {
            get {
                return ResourceManager.GetString("testEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Tryb TEST&lt;/h1&gt;.
        /// </summary>
        internal static string testInfoHeader {
            get {
                return ResourceManager.GetString("testInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;W tym trybie testowana jest poprawność działania programu w sterowniku PLC.&lt;/p&gt; &lt;p&gt;Naciśnij przycisk &gt;Rozpocznij symulację&lt; aby sprawdzić poprawnośc programu w sterowniku.&lt;/p&gt; &lt;p&gt;Wyniki testu będą wyświetlane poniżej:&lt;/p&gt;.
        /// </summary>
        internal static string testInfoInfo {
            get {
                return ResourceManager.GetString("testInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;style type=\&quot;text/css\&quot;&gt; h1 { color: Black; text-decoration:underline; text-align:center } h2 { color: Black; text-decoration:underline } h3 { color: Black; text-decoration:underline } p.pitalic { color: Black; font-style:italic } li.liabc { list-style-type:lower-alpha } li.lidot { list-style-type:disc } td.tdTitle { background-color:Gray; border:2 } td.tdContent { text-align: center } td.tdRed { color: Red }&lt;/style&gt;&lt;body&gt;.
        /// </summary>
        internal static string testInfoMain {
            get {
                return ResourceManager.GetString("testInfoMain", resourceCulture);
            }
        }
    }
}
