//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.ACMotor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLCEmulator.ACMotor.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia silnika trójfazowego.
        /// </summary>
        internal static string msgACmotorSettings {
            get {
                return ResourceManager.GetString("msgACmotorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BŁĄD OBWODU.
        /// </summary>
        internal static string msgBadConnection {
            get {
                return ResourceManager.GetString("msgBadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość ruchu ciężarka.
        /// </summary>
        internal static string msgMoveingSpeed {
            get {
                return ResourceManager.GetString("msgMoveingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z urządzeniem.
        /// </summary>
        internal static string msgNoConnection {
            get {
                return ResourceManager.GetString("msgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYŁĄCZ SILNIK.
        /// </summary>
        internal static string msgOverheat {
            get {
                return ResourceManager.GetString("msgOverheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeciązenie.
        /// </summary>
        internal static string msgOverload {
            get {
                return ResourceManager.GetString("msgOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj symulację.
        /// </summary>
        internal static string msgPauseSimulation {
            get {
                return ResourceManager.GetString("msgPauseSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obracanie w lewo.
        /// </summary>
        internal static string msgRotateLeft {
            get {
                return ResourceManager.GetString("msgRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obracanie w prawo.
        /// </summary>
        internal static string msgRotateRight {
            get {
                return ResourceManager.GetString("msgRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość symulacji.
        /// </summary>
        internal static string msgSimulationSpeed {
            get {
                return ResourceManager.GetString("msgSimulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom symulację.
        /// </summary>
        internal static string msgStartSimulation {
            get {
                return ResourceManager.GetString("msgStartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij test.
        /// </summary>
        internal static string msgStartTest {
            get {
                return ResourceManager.GetString("msgStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj.
        /// </summary>
        internal static string msgStop {
            get {
                return ResourceManager.GetString("msgStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj test.
        /// </summary>
        internal static string msgStopTest {
            get {
                return ResourceManager.GetString("msgStopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSTRZEŻENIE.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie styki wyłączone.
        /// </summary>
        internal static string testAllOff {
            get {
                return ResourceManager.GetString("testAllOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączony styk.
        /// </summary>
        internal static string testCoilOff {
            get {
                return ResourceManager.GetString("testCoilOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włączony styk.
        /// </summary>
        internal static string testCoilOn {
            get {
                return ResourceManager.GetString("testCoilOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie w trójkąt.
        /// </summary>
        internal static string testDConn {
            get {
                return ResourceManager.GetString("testDConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec testu.
        /// </summary>
        internal static string testEnd {
            get {
                return ResourceManager.GetString("testEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończony błędem.
        /// </summary>
        internal static string testError {
            get {
                return ResourceManager.GetString("testError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończono ten etap testu z powodu błędnego stanu na wyjściach PLC.
        /// </summary>
        internal static string testErrorPLC {
            get {
                return ResourceManager.GetString("testErrorPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończono ten etap testu z powodu przekroczenia dopuszczalnego czasu na wystawienie odpowiedniego stanu przez PLC.
        /// </summary>
        internal static string testErrorTime {
            get {
                return ResourceManager.GetString("testErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Tryb TEST&lt;/h1&gt;.
        /// </summary>
        internal static string testInfoHeader {
            get {
                return ResourceManager.GetString("testInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;W tym trybie testowana jest poprawność działania programu w sterowniku PLC.&lt;/p&gt; &lt;p&gt;Naciśnij przycisk &gt;Rozpocznij symulację&lt; aby sprawdzić poprawnośc programu w sterowniku.&lt;/p&gt; &lt;p&gt;Wyniki testu będą wyświetlane poniżej:&lt;/p&gt;.
        /// </summary>
        internal static string testInfoInfo {
            get {
                return ResourceManager.GetString("testInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;style type=\&quot;text/css\&quot;&gt; h1 { color: Black; text-decoration:underline; text-align:center } h2 { color: Black; text-decoration:underline } h3 { color: Black; text-decoration:underline } p.pitalic { color: Black; font-style:italic } li.liabc { list-style-type:lower-alpha } li.lidot { list-style-type:disc } td.tdTitle { background-color:Gray; border:2 } td.tdContent { text-align: center } td.tdRed { color: Red }&lt;/style&gt;&lt;body&gt;.
        /// </summary>
        internal static string testInfoMain {
            get {
                return ResourceManager.GetString("testInfoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Lewej krancówki&quot;.
        /// </summary>
        internal static string testLimitSwitch {
            get {
                return ResourceManager.GetString("testLimitSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można wykonać testu ponieważ sterownik nie przeszedł testu &quot;Obroty w lewo&quot;.
        /// </summary>
        internal static string testNoLeftLimitTest {
            get {
                return ResourceManager.GetString("testNoLeftLimitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można wykonać testu z powodu niewłaściwych stanów na wyjściach PLC.
        /// </summary>
        internal static string testNoOverload {
            get {
                return ResourceManager.GetString("testNoOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Przeciążenia&quot;.
        /// </summary>
        internal static string testOverload {
            get {
                return ResourceManager.GetString("testOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończony powodzeniem.
        /// </summary>
        internal static string testPass {
            get {
                return ResourceManager.GetString("testPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        internal static string testPLC {
            get {
                return ResourceManager.GetString("testPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Obroty w lewo&quot;.
        /// </summary>
        internal static string testSL {
            get {
                return ResourceManager.GetString("testSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Obroty w prawo&quot;.
        /// </summary>
        internal static string testSR {
            get {
                return ResourceManager.GetString("testSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Stop&quot;.
        /// </summary>
        internal static string testSTOP {
            get {
                return ResourceManager.GetString("testSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie w gwiazdę.
        /// </summary>
        internal static string testYConn {
            get {
                return ResourceManager.GetString("testYConn", resourceCulture);
            }
        }
    }
}
