//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ACMotor : global::System.Configuration.ApplicationSettingsBase {
        
        private static ACMotor defaultInstance = ((ACMotor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ACMotor())));
        
        public static ACMotor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double MoveingSpeed {
            get {
                return ((double)(this["MoveingSpeed"]));
            }
            set {
                this["MoveingSpeed"] = value;
            }
        }
    }
}
