//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.Reactor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLCEmulator.Reactor.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stałoprocentowy.
        /// </summary>
        internal static string msgConstant {
            get {
                return ResourceManager.GetString("msgConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry toru stygnięcia.
        /// </summary>
        internal static string msgCoolDownParameters {
            get {
                return ResourceManager.GetString("msgCoolDownParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chłodzenie.
        /// </summary>
        internal static string msgCooling {
            get {
                return ResourceManager.GetString("msgCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry toru chłodzenia.
        /// </summary>
        internal static string msgCoolingParameters {
            get {
                return ResourceManager.GetString("msgCoolingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura wody chłodzącej.
        /// </summary>
        internal static string msgCoolingWaterTemperature {
            get {
                return ResourceManager.GetString("msgCoolingWaterTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cykl.
        /// </summary>
        internal static string msgCycle {
            get {
                return ResourceManager.GetString("msgCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opóżnienie.
        /// </summary>
        internal static string msgDelay {
            get {
                return ResourceManager.GetString("msgDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opróżnianie.
        /// </summary>
        internal static string msgEmptying {
            get {
                return ResourceManager.GetString("msgEmptying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura otoczenia.
        /// </summary>
        internal static string msgEnvironmentTemperature {
            get {
                return ResourceManager.GetString("msgEnvironmentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napełnianie.
        /// </summary>
        internal static string msgFilling {
            get {
                return ResourceManager.GetString("msgFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogrzewanie.
        /// </summary>
        internal static string msgHeating {
            get {
                return ResourceManager.GetString("msgHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry toru grzania.
        /// </summary>
        internal static string msgHeatingParameters {
            get {
                return ResourceManager.GetString("msgHeatingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość początkowa wypełnienia.
        /// </summary>
        internal static string msgInitialFill {
            get {
                return ResourceManager.GetString("msgInitialFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość przepływu dla składnika.
        /// </summary>
        internal static string msgInitialFlow {
            get {
                return ResourceManager.GetString("msgInitialFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laminarny.
        /// </summary>
        internal static string msgLaminar {
            get {
                return ResourceManager.GetString("msgLaminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liniowy.
        /// </summary>
        internal static string msgLinear {
            get {
                return ResourceManager.GetString("msgLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współczynnik skalowania dla mieszadła.
        /// </summary>
        internal static string msgMixerRatio {
            get {
                return ResourceManager.GetString("msgMixerRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z urządzeniem.
        /// </summary>
        internal static string msgNoConnection {
            get {
                return ResourceManager.GetString("msgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj odpływu.
        /// </summary>
        internal static string msgOutflowingValveType {
            get {
                return ResourceManager.GetString("msgOutflowingValveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość przepływu dla zaworu odpływowego.
        /// </summary>
        internal static string msgOutflowValveValue {
            get {
                return ResourceManager.GetString("msgOutflowValveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRZEPEŁNIENIE.
        /// </summary>
        internal static string msgOverfill {
            get {
                return ResourceManager.GetString("msgOverfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRZEGRZANIE.
        /// </summary>
        internal static string msgOverheat {
            get {
                return ResourceManager.GetString("msgOverheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj symulację.
        /// </summary>
        internal static string msgPauseSimulation {
            get {
                return ResourceManager.GetString("msgPauseSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ reakcji.
        /// </summary>
        internal static string msgReactionType {
            get {
                return ResourceManager.GetString("msgReactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia reaktora.
        /// </summary>
        internal static string msgReactorSettings {
            get {
                return ResourceManager.GetString("msgReactorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości zadane.
        /// </summary>
        internal static string msgSetPointValues {
            get {
                return ResourceManager.GetString("msgSetPointValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość symulacji.
        /// </summary>
        internal static string msgSimulationSpeed {
            get {
                return ResourceManager.GetString("msgSimulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilizacja.
        /// </summary>
        internal static string msgStabilization {
            get {
                return ResourceManager.GetString("msgStabilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom symulację.
        /// </summary>
        internal static string msgStartSimulation {
            get {
                return ResourceManager.GetString("msgStartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij test.
        /// </summary>
        internal static string msgStartTest {
            get {
                return ResourceManager.GetString("msgStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura pary.
        /// </summary>
        internal static string msgSteamTemperature {
            get {
                return ResourceManager.GetString("msgSteamTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj zaworu pary grzejącej.
        /// </summary>
        internal static string msgSteamValveType {
            get {
                return ResourceManager.GetString("msgSteamValveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj test.
        /// </summary>
        internal static string msgStopTest {
            get {
                return ResourceManager.GetString("msgStopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stała czasowa.
        /// </summary>
        internal static string msgTimeConstant {
            get {
                return ResourceManager.GetString("msgTimeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turbulentny.
        /// </summary>
        internal static string msgTurbulent {
            get {
                return ResourceManager.GetString("msgTurbulent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSTRZEŻENIE.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączone wyjście analogowe.
        /// </summary>
        internal static string testAnalogOff {
            get {
                return ResourceManager.GetString("testAnalogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włączone wyjście analogowe.
        /// </summary>
        internal static string testAnalogOn {
            get {
                return ResourceManager.GetString("testAnalogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Chłodzenie&quot;.
        /// </summary>
        internal static string testCooling {
            get {
                return ResourceManager.GetString("testCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączony styk.
        /// </summary>
        internal static string testDigitalOff {
            get {
                return ResourceManager.GetString("testDigitalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włączony styk.
        /// </summary>
        internal static string testDigitalOn {
            get {
                return ResourceManager.GetString("testDigitalOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Opróżnianie&quot;.
        /// </summary>
        internal static string testEmptying {
            get {
                return ResourceManager.GetString("testEmptying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec testu.
        /// </summary>
        internal static string testEnd {
            get {
                return ResourceManager.GetString("testEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończony błędem.
        /// </summary>
        internal static string testError {
            get {
                return ResourceManager.GetString("testError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończono ten etap testu z powodu błędnego stanu na wyjściach PLC.
        /// </summary>
        internal static string testErrorPLC {
            get {
                return ResourceManager.GetString("testErrorPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończono ten etap testu z powodu przekroczenia dopuszczalnego czasu na wystawienie odpowiedniego stanu przez PLC.
        /// </summary>
        internal static string testErrorTime {
            get {
                return ResourceManager.GetString("testErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Napełnianie&quot;.
        /// </summary>
        internal static string testFilling {
            get {
                return ResourceManager.GetString("testFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: &quot;Podgrzewanie&quot;.
        /// </summary>
        internal static string testHeating {
            get {
                return ResourceManager.GetString("testHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Tryb TEST&lt;/h1&gt;.
        /// </summary>
        internal static string testInfoHeader {
            get {
                return ResourceManager.GetString("testInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;W tym trybie testowana jest poprawność działania programu w sterowniku PLC.&lt;/p&gt; &lt;p&gt;Naciśnij przycisk &gt;Rozpocznij symulację&lt; aby sprawdzić poprawnośc programu w sterowniku.&lt;/p&gt; &lt;p&gt;Wyniki testu będą wyświetlane poniżej:&lt;/p&gt;.
        /// </summary>
        internal static string testInfoInfo {
            get {
                return ResourceManager.GetString("testInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;style type=\&quot;text/css\&quot;&gt; h1 { color: Black; text-decoration:underline; text-align:center } h2 { color: Black; text-decoration:underline } h3 { color: Black; text-decoration:underline } p.pitalic { color: Black; font-style:italic } li.liabc { list-style-type:lower-alpha } li.lidot { list-style-type:disc } td.tdTitle { background-color:Gray; border:2 } td.tdContent { text-align: center } td.tdRed { color: Red }&lt;/style&gt;&lt;body&gt;.
        /// </summary>
        internal static string testInfoMain {
            get {
                return ResourceManager.GetString("testInfoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastąpiło przepełnienie reaktora.
        /// </summary>
        internal static string testOverfillError {
            get {
                return ResourceManager.GetString("testOverfillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastąpiło przegrzanie reaktora.
        /// </summary>
        internal static string testOverheatError {
            get {
                return ResourceManager.GetString("testOverheatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie przeregulowania.
        /// </summary>
        internal static string testOvershot {
            get {
                return ResourceManager.GetString("testOvershot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeregulowanie.
        /// </summary>
        internal static string testOvershotBorders {
            get {
                return ResourceManager.GetString("testOvershotBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie osiągnięto wartości zadanej w pożadanym czasie.
        /// </summary>
        internal static string testOvershotError {
            get {
                return ResourceManager.GetString("testOvershotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończony powodzeniem.
        /// </summary>
        internal static string testPass {
            get {
                return ResourceManager.GetString("testPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        internal static string testPLC {
            get {
                return ResourceManager.GetString("testPLC", resourceCulture);
            }
        }
    }
}
