//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLCEmulator.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1 { color: Black; text-decoration:underline; text-align:center }
        ///        h2 { color: Black; text-decoration:underline }
        ///        h3 { color: Black; text-decoration:underline }
        ///        p.pitalic { color: Black; font-style:italic }
        ///        li.liabc { list-style-type:lower-alpha }
        ///        li.lidot { list-style-type:disc }
        ///        td.tdTitle { border-style: none;
        ///            border-color: inherit;
        ///            border-width: 2;
        ///            background-color:Gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACMotorHLP {
            get {
                return ResourceManager.GetString("ACMotorHLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaczenia.
        /// </summary>
        internal static string menuCaptions {
            get {
                return ResourceManager.GetString("menuCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz.
        /// </summary>
        internal static string menuConnect {
            get {
                return ResourceManager.GetString("menuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozłącz.
        /// </summary>
        internal static string menuDisconnect {
            get {
                return ResourceManager.GetString("menuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        internal static string menuOptions {
            get {
                return ResourceManager.GetString("menuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silnik trójfazowy.
        /// </summary>
        internal static string msgACMotor {
            get {
                return ResourceManager.GetString("msgACMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string msgDemo {
            get {
                return ResourceManager.GetString("msgDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z urządzeniem.
        /// </summary>
        internal static string msgNoConnection {
            get {
                return ResourceManager.GetString("msgNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objaśnienie.
        /// </summary>
        internal static string msgObjasnienia {
            get {
                return ResourceManager.GetString("msgObjasnienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string msgOK {
            get {
                return ResourceManager.GetString("msgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaktor.
        /// </summary>
        internal static string msgReactor {
            get {
                return ResourceManager.GetString("msgReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string msgSettings {
            get {
                return ResourceManager.GetString("msgSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symulacja.
        /// </summary>
        internal static string msgSimulation {
            get {
                return ResourceManager.GetString("msgSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sygnalizacja.
        /// </summary>
        internal static string msgSygnalizacja {
            get {
                return ResourceManager.GetString("msgSygnalizacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SygnalizacjaII.
        /// </summary>
        internal static string msgSygnalizacjaII {
            get {
                return ResourceManager.GetString("msgSygnalizacjaII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SygnalizacjaIII.
        /// </summary>
        internal static string msgSygnalizacjaIII {
            get {
                return ResourceManager.GetString("msgSygnalizacjaIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string msgTest {
            get {
                return ResourceManager.GetString("msgTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel testowy.
        /// </summary>
        internal static string msgTestPannel {
            get {
                return ResourceManager.GetString("msgTestPannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1 { color: Black; text-decoration:underline; text-align:center }
        ///        h2 { color: Black; text-decoration:underline }
        ///        h3 { color: Black; text-decoration:underline }
        ///        p.pitalic { color: Black; font-style:italic }
        ///        li.liabc { list-style-type:lower-alpha }
        ///        li.lidot { list-style-type:disc }
        ///        li.li123 { list-style-type:decimal }
        ///        td.tdTitle { border-style: none;
        ///            border-color: inherit;
        ///            bord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReactorHLP {
            get {
                return ResourceManager.GetString("ReactorHLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogowe.
        /// </summary>
        internal static string settingsWndAnalog {
            get {
                return ResourceManager.GetString("settingsWndAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitu.
        /// </summary>
        internal static string settingsWndBit {
            get {
                return ResourceManager.GetString("settingsWndBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitowa.
        /// </summary>
        internal static string settingsWndBits {
            get {
                return ResourceManager.GetString("settingsWndBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bajtu.
        /// </summary>
        internal static string settingsWndByte {
            get {
                return ResourceManager.GetString("settingsWndByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyfrowe.
        /// </summary>
        internal static string settingsWndDiscrete {
            get {
                return ResourceManager.GetString("settingsWndDiscrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wejścia.
        /// </summary>
        internal static string settingsWndInputs {
            get {
                return ResourceManager.GetString("settingsWndInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalna.
        /// </summary>
        internal static string settingsWndNormal {
            get {
                return ResourceManager.GetString("settingsWndNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjścia.
        /// </summary>
        internal static string settingsWndOutputs {
            get {
                return ResourceManager.GetString("settingsWndOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz ustawienie.
        /// </summary>
        internal static string settingsWndSaveSettings {
            get {
                return ResourceManager.GetString("settingsWndSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz ustawienie jako.
        /// </summary>
        internal static string settingsWndSaveSettingsAs {
            get {
                return ResourceManager.GetString("settingsWndSaveSettingsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia użytkownika.
        /// </summary>
        internal static string settingsWndSettings {
            get {
                return ResourceManager.GetString("settingsWndSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez odstępów między znakami.
        /// </summary>
        internal static string settingsWndSettingsInfo {
            get {
                return ResourceManager.GetString("settingsWndSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa ustawienia.
        /// </summary>
        internal static string settingsWndSettingsName {
            get {
                return ResourceManager.GetString("settingsWndSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz typ.
        /// </summary>
        internal static string settingsWndSetType {
            get {
                return ResourceManager.GetString("settingsWndSetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość poczatkowa.
        /// </summary>
        internal static string settingsWndStartValue {
            get {
                return ResourceManager.GetString("settingsWndStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string settingsWndSymbol {
            get {
                return ResourceManager.GetString("settingsWndSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia etykiet.
        /// </summary>
        internal static string settingsWndTitle {
            get {
                return ResourceManager.GetString("settingsWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        internal static string settingsWndView {
            get {
                return ResourceManager.GetString("settingsWndView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeracja.
        /// </summary>
        internal static string settingsWngNumeration {
            get {
                return ResourceManager.GetString("settingsWngNumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1 { color: Black; text-decoration:underline; text-align:center }
        ///        h2 { color: Black; text-decoration:underline }
        ///        h3 { color: Black; text-decoration:underline }
        ///        p.pitalic { color: Black; font-style:italic }
        ///        li.liabc { list-style-type:lower-alpha }
        ///        li.lidot { list-style-type:disc }
        ///        li.li123 { list-style-type:decimal }
        ///        td.tdTitle { border-style: none;
        ///            border-color: inherit;
        ///            bord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SygnalizacjaHLP {
            get {
                return ResourceManager.GetString("SygnalizacjaHLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1 { color: Black; text-decoration:underline; text-align:center }
        ///        h2 { color: Black; text-decoration:underline }
        ///        h3 { color: Black; text-decoration:underline }
        ///        p.pitalic { color: Black; font-style:italic }
        ///        li.liabc { list-style-type:lower-alpha }
        ///        li.lidot { list-style-type:disc }
        ///        li.li123 { list-style-type:decimal }
        ///        td.tdTitle { border-style: none;
        ///            border-color: inherit;
        ///            bord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SygnalizacjaIIHLP {
            get {
                return ResourceManager.GetString("SygnalizacjaIIHLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1 { color: Black; text-decoration:underline; text-align:center }
        ///        h2 { color: Black; text-decoration:underline }
        ///        h3 { color: Black; text-decoration:underline }
        ///        p.pitalic { color: Black; font-style:italic }
        ///        li.liabc { list-style-type:lower-alpha }
        ///        li.lidot { list-style-type:disc }
        ///        li.li123 { list-style-type:decimal }
        ///        td.tdTitle { border-style: none;
        ///            border-color: inherit;
        ///            bord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SygnalizacjaIIIHLP {
            get {
                return ResourceManager.GetString("SygnalizacjaIIIHLP", resourceCulture);
            }
        }
    }
}
