//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Reactor : global::System.Configuration.ApplicationSettingsBase {
        
        private static Reactor defaultInstance = ((Reactor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Reactor())));
        
        public static Reactor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double InitialPercentageFilling {
            get {
                return ((double)(this["InitialPercentageFilling"]));
            }
            set {
                this["InitialPercentageFilling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double InitialAFlow {
            get {
                return ((double)(this["InitialAFlow"]));
            }
            set {
                this["InitialAFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double InitialBFlow {
            get {
                return ((double)(this["InitialBFlow"]));
            }
            set {
                this["InitialBFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutflowingValveType {
            get {
                return ((bool)(this["OutflowingValveType"]));
            }
            set {
                this["OutflowingValveType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double OutflowValveValue {
            get {
                return ((double)(this["OutflowValveValue"]));
            }
            set {
                this["OutflowValveValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public double SteamTemperature {
            get {
                return ((double)(this["SteamTemperature"]));
            }
            set {
                this["SteamTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double CoolingWaterTemperature {
            get {
                return ((double)(this["CoolingWaterTemperature"]));
            }
            set {
                this["CoolingWaterTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double MixerRatio {
            get {
                return ((double)(this["MixerRatio"]));
            }
            set {
                this["MixerRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SteamValveType {
            get {
                return ((bool)(this["SteamValveType"]));
            }
            set {
                this["SteamValveType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double HeatingT1 {
            get {
                return ((double)(this["HeatingT1"]));
            }
            set {
                this["HeatingT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double HeatingT2 {
            get {
                return ((double)(this["HeatingT2"]));
            }
            set {
                this["HeatingT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double HeatingTdelay {
            get {
                return ((double)(this["HeatingTdelay"]));
            }
            set {
                this["HeatingTdelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double CoolingT3 {
            get {
                return ((double)(this["CoolingT3"]));
            }
            set {
                this["CoolingT3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CoolingTdelay {
            get {
                return ((double)(this["CoolingTdelay"]));
            }
            set {
                this["CoolingTdelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double CoolDownTn {
            get {
                return ((double)(this["CoolDownTn"]));
            }
            set {
                this["CoolDownTn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double EnvironmentTemperature {
            get {
                return ((double)(this["EnvironmentTemperature"]));
            }
            set {
                this["EnvironmentTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double CoolDownTdelay {
            get {
                return ((double)(this["CoolDownTdelay"]));
            }
            set {
                this["CoolDownTdelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ReactionType {
            get {
                return ((double)(this["ReactionType"]));
            }
            set {
                this["ReactionType"] = value;
            }
        }
    }
}
