//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLCEmulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%DO")]
        public string PLCDOStartSymbol {
            get {
                return ((string)(this["PLCDOStartSymbol"]));
            }
            set {
                this["PLCDOStartSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%DI")]
        public string PLCDIStartSymbol {
            get {
                return ((string)(this["PLCDIStartSymbol"]));
            }
            set {
                this["PLCDIStartSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%AO")]
        public string PLCAOStartSymbol {
            get {
                return ((string)(this["PLCAOStartSymbol"]));
            }
            set {
                this["PLCAOStartSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%AI")]
        public string PLCAIStartSymbol {
            get {
                return ((string)(this["PLCAIStartSymbol"]));
            }
            set {
                this["PLCAIStartSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCChoice {
            get {
                return ((int)(this["PLCChoice"]));
            }
            set {
                this["PLCChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDOStartValue {
            get {
                return ((int)(this["PLCDOStartValue"]));
            }
            set {
                this["PLCDOStartValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDIStartValue {
            get {
                return ((int)(this["PLCDIStartValue"]));
            }
            set {
                this["PLCDIStartValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAOStartValue {
            get {
                return ((int)(this["PLCAOStartValue"]));
            }
            set {
                this["PLCAOStartValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAIStartValue {
            get {
                return ((int)(this["PLCAIStartValue"]));
            }
            set {
                this["PLCAIStartValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDOStartValueBit {
            get {
                return ((int)(this["PLCDOStartValueBit"]));
            }
            set {
                this["PLCDOStartValueBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDIStartValueBit {
            get {
                return ((int)(this["PLCDIStartValueBit"]));
            }
            set {
                this["PLCDIStartValueBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAOStartValueBit {
            get {
                return ((int)(this["PLCAOStartValueBit"]));
            }
            set {
                this["PLCAOStartValueBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAIStartValueBit {
            get {
                return ((int)(this["PLCAIStartValueBit"]));
            }
            set {
                this["PLCAIStartValueBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDOBit {
            get {
                return ((int)(this["PLCDOBit"]));
            }
            set {
                this["PLCDOBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCDIBit {
            get {
                return ((int)(this["PLCDIBit"]));
            }
            set {
                this["PLCDIBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAOBit {
            get {
                return ((int)(this["PLCAOBit"]));
            }
            set {
                this["PLCAOBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLCAIBit {
            get {
                return ((int)(this["PLCAIBit"]));
            }
            set {
                this["PLCAIBit"] = value;
            }
        }
    }
}
